// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"EnemyBattleLayout","status":true,"description":"敵人縮小30%、靠左、攻擊踏步前衝","parameters":{"defaultScale":"70","homeX":"200","homeY":"360","attackStep":"48","useHomeOverride":"true"}},
{"name":"EnemyScale","status":false,"description":"(replaced by EnemyBattleLayout)","parameters":{}}
];
