// cachebust 20260917b
// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[{"name":"EnemyBattleLayout","status":true,"description":"enemy scale 70% left attack step","parameters":{"defaultScale":"70","homeX":"200","homeY":"360","attackStep":"48","useHomeOverride":"true"}},{"name":"EnemyScale","status":false,"description":"replaced","parameters":{}}];
